# -*- coding: utf-8 -*-
"""
Module responsible for loading individual page images.

This module takes a file path (presumably to a temporary image file
generated by pdf_splitter) and loads it into a suitable format
for further processing (e.g., a PIL Image object).
"""

import os
import sys
from PIL import Image, UnidentifiedImageError # Import Pillow for image handling and specific error

def load_page_image(image_path: str) -> Image.Image | None:
    """
    Loads a page image from the specified file path.

    Args:
        image_path: The path to the image file (e.g., a temporary .webp file).

    Returns:
        A PIL Image object if loading is successful.

    Raises:
        FileNotFoundError: If the image_path does not exist or is not a file.
        UnidentifiedImageError: If the file cannot be opened as a valid image format by Pillow.
        Exception: For other potential OS or permission errors during file access.
    """
    print(f"Attempting to load page image from: {image_path}")

    # Validate if the path exists and is a file
    if not os.path.isfile(image_path):
        # This might happen if the path yielded by the splitter is incorrect
        # or the temporary file was deleted unexpectedly.
        error_msg = f"Image file not found or is not a file at path: {image_path}"
        print(f"Error: {error_msg}", file=sys.stderr)
        raise FileNotFoundError(error_msg)

    try:
        # Open the image file using Pillow
        # This automatically detects the format (like WebP)
        img = Image.open(image_path)

        # It's often useful to load the image data into memory immediately
        # if the file might be deleted or changed before processing is complete.
        # This also catches potential decoding errors early.
        img.load()

        print(f"  Successfully loaded image: mode={img.mode}, size={img.size}")
        # Return the PIL Image object for downstream processing
        return img

    except UnidentifiedImageError as e:
        # This happens if Pillow doesn't recognize the image format or the file is corrupted
        error_msg = f"Cannot identify image file. It might be corrupted or an unsupported format: {image_path}. Error: {e}"
        print(f"Error: {error_msg}", file=sys.stderr)
        raise UnidentifiedImageError(error_msg) from e # Re-raise with context

    except Exception as e:
        # Catch other potential errors (e.g., permissions, OS errors)
        error_msg = f"An unexpected error occurred loading image '{image_path}': {e}"
        print(f"Error: {error_msg}", file=sys.stderr)
        raise Exception(error_msg) from e # Re-raise other errors with context

# Example usage block (for testing when script is run directly)
if __name__ == "__main__":
    print("\n--- Running loader.py directly for testing ---")
    # This requires a sample image file to exist.
    # For standalone testing, create a dummy image or point to an existing one.

    # Define a path for a dummy test image
    test_image_dir = "temp_test_loader"
    os.makedirs(test_image_dir, exist_ok=True) # Ensure test dir exists
    test_image_path = os.path.join(test_image_dir, "test_loader_image.webp")

    try:
        # Create a small dummy WebP image for testing if it doesn't exist
        if not os.path.exists(test_image_path):
            print(f"Creating dummy test image: {test_image_path}")
            dummy_img = Image.new('RGB', (60, 30), color = 'blue')
            dummy_img.save(test_image_path, "webp", lossless=True)
            dummy_img.close()

        # --- Test Case 1: Load valid image ---
        print(f"\nTesting loading valid image: {test_image_path}")
        loaded_image = load_page_image(test_image_path)
        if loaded_image:
            print("  Test load successful! Image details:")
            print(f"    Format: {loaded_image.format}")
            print(f"    Size: {loaded_image.size}")
            print(f"    Mode: {loaded_image.mode}")
            loaded_image.close() # Close the image after inspection
        else:
            # This part should ideally not be reached if load_page_image raises exceptions on failure
            print("  Test load failed unexpectedly (returned None).")

    except (FileNotFoundError, UnidentifiedImageError, Exception) as e:
         print(f"  Test Error for valid image: {e}")


    # --- Test Case 2: Load non-existent file ---
    non_existent_path = os.path.join(test_image_dir, "non_existent_image.webp")
    print(f"\nTesting non-existent file: {non_existent_path}")
    try:
        load_page_image(non_existent_path)
        print("  Error: Expected FileNotFoundError but none was raised.") # Should not happen
    except FileNotFoundError:
        print("  Successfully caught FileNotFoundError (expected).")
    except Exception as e:
        print(f"  Caught unexpected error for non-existent file: {e}")


    # --- Test Case 3: Load an invalid image file (e.g., a text file) ---
    invalid_image_path = os.path.join(test_image_dir, "invalid_image.txt")
    print(f"\nTesting invalid image file: {invalid_image_path}")
    try:
        # Create a dummy text file
        with open(invalid_image_path, "w") as f:
            f.write("This is not an image.")

        load_page_image(invalid_image_path)
        print("  Error: Expected UnidentifiedImageError but none was raised.") # Should not happen
    except UnidentifiedImageError:
        print("  Successfully caught UnidentifiedImageError (expected).")
    except Exception as e:
        print(f"  Caught unexpected error for invalid file: {e}")


    finally:
        # Clean up dummy files and directory
        print("\nCleaning up test files...")
        paths_to_remove = [test_image_path, invalid_image_path]
        for p in paths_to_remove:
            if os.path.exists(p):
                try:
                    os.remove(p)
                    print(f"  Removed: {p}")
                except OSError as e:
                    print(f"  Error removing {p}: {e}", file=sys.stderr)
        try:
            if os.path.exists(test_image_dir):
                os.rmdir(test_image_dir) # Remove directory if empty
                print(f"  Removed test directory: {test_image_dir}")
        except OSError as e:
             print(f"  Note: Could not remove test directory {test_image_dir}: {e}", file=sys.stderr)


    print("\n--- Loader Test Complete ---")